ROUTINE CriarLogMensagem

CriarLogMensagem
    set pDataInicio = ##Class(%UTC).NowLocal()
    set pStatus = 1
    set pClasse = "LogMensagem"
    set pMetodo = "LogMetodo"
    set pStatusProcesso="Processo realizado com sucesso!"
    set pStatusCode = "1"
    set pPageSize = 10
    set pDataFim = "" //$zd($h,4)
    set pLastId = 1

    set LogMensagemCriar = ##Class(Treinamento.Data.LogMensagem).CriarEntrada(pMetodo, pClasse)
    set IdLog = LogMensagemCriar.%Id()

    set LogMensagemCriar = ##Class(Treinamento.Data.LogMensagem).Finalizar(IdLog, pStatusProcesso, pStatusCode)

    set objConsultaLog = ##Class(Treinamento.Data.LogMensagem).ConsultaLog(pStatus)
    for i=1:1:objConsultaLog.ListaLog.Count() {
        set item = objConsultaLog.ListaLog.GetAt(i)
        Write "Item: ", i, !
        Write "Metodo: ", item.Metodo, !
        Write "Classe: ", item.Classe, !
        Write "Data Inicio: ", item.Inicio, !
        Write "Data Fim: ", item.Fim, !
        Write "Status: ", item.Status, !
        Write "Status Processo: ", item.StatusProcesso, !!
    }

    Set objLogPaginado = ##class(Treinamento.Data.LogMensagem).ConsultaLogPaginacao(pStatus, pLastId, pPageSize, pDataFim)
    For i=1:1:objLogPaginado.ListaLog.Count() {
        Set item = objLogPaginado.ListaLog.GetAt(i)       
        Write " ID : ", item.ID, " | Metodo : ", item.Metodo, " | Classe : ", item.Classe, "| Status : ", item.Status, !     
       
        Write ! 
    }